/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Stock.h"


void
<<<<<<< HEAD
distributionballon_1(char *host)
{
	CLIENT *clnt;
	reponse1  *result_1;
	data1  distribution_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, distributionballon, VERSION_UN, "udp");
=======
validation_1(char *host)
{
	CLIENT *clnt;
	reponse1  *result_1;
	data1  validation_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, Validation, VERSION_UN, "udp");
>>>>>>> 06165ad47ec004befbee37b1cdafff274e9f7f76
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

<<<<<<< HEAD
	result_1 = distribution_1(&distribution_1_arg, clnt);
=======
	result_1 = validation_1(&validation_1_arg, clnt);
>>>>>>> 06165ad47ec004befbee37b1cdafff274e9f7f76
	if (result_1 == (reponse1 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
<<<<<<< HEAD
validationballon_1(char *host)
{
	CLIENT *clnt;
	reponse2  *result_1;
	data2  validation_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, validationballon, VERSION_UN, "udp");
=======
distribution_2(char *host)
{
	CLIENT *clnt;
	reponse2  *result_1;
	data2  distribution_2_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, distribution, VERSION_UN, "udp");
>>>>>>> 06165ad47ec004befbee37b1cdafff274e9f7f76
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

<<<<<<< HEAD
	result_1 = validation_1(&validation_1_arg, clnt);
=======
	result_1 = distribution_2(&distribution_2_arg, clnt);
>>>>>>> 06165ad47ec004befbee37b1cdafff274e9f7f76
	if (result_1 == (reponse2 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
<<<<<<< HEAD
	distributionballon_1 (host);
	validationballon_1 (host);
=======
	validation_1 (host);
	distribution_2 (host);
>>>>>>> 06165ad47ec004befbee37b1cdafff274e9f7f76
exit (0);
}
