/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Stock.h"


void
distributionballon_1(char *host)
{
	CLIENT *clnt;
	reponse1  *result_1;
	data1  distribution_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, distributionballon, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = distribution_1(&distribution_1_arg, clnt);
	if (result_1 == (reponse1 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
validationballon_1(char *host)
{
	CLIENT *clnt;
	reponse2  *result_1;
	data2  validation_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, validationballon, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = validation_1(&validation_1_arg, clnt);
	if (result_1 == (reponse2 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	distributionballon_1 (host);
	validationballon_1 (host);
exit (0);
}
