/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Stock.h"

bool_t
xdr_data1 (XDR *xdrs, data1 *objp)
{
	register int32_t *buf;

<<<<<<< HEAD
	int i;
	 if (!xdr_vector (xdrs, (char *)objp->IPjoueur, 32,
		sizeof (char), (xdrproc_t) xdr_char))
=======
	 if (!xdr_int (xdrs, &objp->ballonDispo))
>>>>>>> 06165ad47ec004befbee37b1cdafff274e9f7f76
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reponse1 (XDR *xdrs, reponse1 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->cleballon, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_data2 (XDR *xdrs, data2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->cleballon, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
<<<<<<< HEAD
xdr_reponse2 (XDR *xdrs, reponse2 *objp)
=======
xdr_reponse1 (XDR *xdrs, reponse1 *objp)
>>>>>>> 06165ad47ec004befbee37b1cdafff274e9f7f76
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ok))
		 return FALSE;
	return TRUE;
}
