/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STOCK_H_RPCGEN
#define _STOCK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data1 {
	char IPjoueur[32];
};
typedef struct data1 data1;


struct reponse1 {
	char cleballon[256];
};
typedef struct reponse1 reponse1;


struct data2 {
	char cleballon[256];
};
typedef struct data2 data2;


struct reponse2 {
	int ok;
};
typedef struct reponse2 reponse2;


#define distributionballon 0x20000001
#define VERSION_UN 1

#if defined(__STDC__) || defined(__cplusplus)
#define distribution 1
extern  reponse1 * distribution_1(data1 *, CLIENT *);
extern  reponse1 * distribution_1_svc(data1 *, struct svc_req *);
extern int distributionballon_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define distribution 1
extern  reponse1 * distribution_1();
extern  reponse1 * distribution_1_svc();
extern int distributionballon_1_freeresult ();
#endif /* K&R C */

#define validationballon 0x20000001
#define VERSION_UN 1

#if defined(__STDC__) || defined(__cplusplus)
#define validation 1
extern  reponse2 * validation_1(data2 *, CLIENT *);
extern  reponse2 * validation_1_svc(data2 *, struct svc_req *);
extern int validationballon_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define validation 1
extern  reponse2 * validation_1();
extern  reponse2 * validation_1_svc();
extern int validationballon_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data1 (XDR *, data1*);
extern  bool_t xdr_data1 (XDR *, data1*);
extern  bool_t xdr_reponse1 (XDR *, reponse1*);
extern  bool_t xdr_reponse1 (XDR *, reponse1*);
extern  bool_t xdr_data2 (XDR *, data2*);
extern  bool_t xdr_data2 (XDR *, data2*);
extern  bool_t xdr_reponse2 (XDR *, reponse2*);
extern  bool_t xdr_reponse2 (XDR *, reponse2*);

#else /* K&R C */
extern bool_t xdr_data1 ();
extern bool_t xdr_data1 ();
extern bool_t xdr_reponse1 ();
extern bool_t xdr_reponse1 ();
extern bool_t xdr_data2 ();
extern bool_t xdr_data2 ();
extern bool_t xdr_reponse2 ();
extern bool_t xdr_reponse2 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STOCK_H_RPCGEN */
