/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Validation.h"
int
validationballon_1(char *host, char *cleballon)
{
	CLIENT *clnt;
	reponse2  *result_1;
	data2  validation_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, validationballon, VERSION_UN, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	strcpy(validation_1_arg.cleballon, cleballon);
	result_1 = validation_1(&validation_1_arg, clnt);
	if (result_1 == (reponse2 *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	return result_1->ok;
}
	
reponse *
validation_1_svc(data *argp, struct svc_req *rqstp)
{
	static reponse  result;

	result.ok= validationballon_1("localhost",argp->cleBallon);

	return &result;
}
