/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Validation.h"

#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define PORT 8000 // port de communication avec le serveur RPC gestion du stock de ballon


reponse *
validation_1_svc(data *argp, struct svc_req *rqstp)
{
	static reponse  result;

	int sock;
	struct sockaddr_in sin;

	/* Creation de la socket client stock de ballon*/
	sock = socket(AF_INET, SOCK_STREAM, 0);

	/* Configuration de la connexion */
	sin.sin_addr.s_addr = inet_addr("127.0.0.1"); // sur la même machine
	sin.sin_family = AF_INET;
	sin.sin_port = htons(PORT);

	/* Tentative de connexion au serveur */
	connect(sock, (struct sockaddr*)&sin, sizeof(sin));
	printf("Connexion a %s sur le port %d\n", inet_ntoa(sin.sin_addr),
	 		htons(sin.sin_port));

	char buffer2[32]="envoi de la liste ballons";

	/* Envoi de donnees au serveur */
	send(sock, buffer2, 32, 0);

	/* Reception de donnees du serveur */
	char buffer[32] = "";
	recv(sock, buffer, 32, 0);
	printf("Recu : %s\n", buffer);
	/* Fermeture de la socket client */
	printf("%s\n", "deconnexion");
return &result;

	return &result;
}
